
ACTIVITY_SIGNED_UP = 0
ACTIVITY_LOGGED_IN = 1
ACTIVITY_SENT_OFF_SITE_INVITE = 2
ACTIVITY_SENT_FRIEND_REQUEST = 3
ACTIVITY_ACCEPTED_FRIEND_REQUEST = 4
ACTIVITY_ESTABLISHED_FRIENDSHIP = 5
ACTIVITY_DECLINED_FRIENDSHIP = 6
ACTIVITY_REVOKED_FRIENDSHIP = 7
ACTIVITY_EARNED_BADGE = 8
ACTIVITY_POSTED = 9
ACTIVITY_UPLOADED_IMAGE = 10
ACTIVITY_COMMENTED = 11
ACTIVITY_LIKED = 12
ACTIVITY_UPDATED_AVATAR = 13
ACTIVITY_UPDATED_PROFILE = 14
ACTIVITY_SENT_MESSAGE = 15
ACTIVITY_SOCIAL_SHARE = 16

ACTIVITY_CHOICES = (
        (ACTIVITY_SIGNED_UP, 'Signed up'),
        (ACTIVITY_LOGGED_IN, 'Logged in'),
        (ACTIVITY_SENT_OFF_SITE_INVITE, 'Sent an off-site invite'),
        (ACTIVITY_SENT_FRIEND_REQUEST, 'Sent friend request'),
        (ACTIVITY_ACCEPTED_FRIEND_REQUEST, 'Accepted friend request'),
        (ACTIVITY_ESTABLISHED_FRIENDSHIP, 'Established friendship'),
        (ACTIVITY_DECLINED_FRIENDSHIP, 'Declined friendship'),
        (ACTIVITY_REVOKED_FRIENDSHIP, 'Revoked friendship'),
        (ACTIVITY_EARNED_BADGE, 'Earned badge'),
        (ACTIVITY_POSTED, 'Added a blog post'),
        (ACTIVITY_UPLOADED_IMAGE, 'Uploaded Image'),
        (ACTIVITY_COMMENTED, 'Added a comment'),
        (ACTIVITY_UPDATED_AVATAR, 'Updated your avatar'),
        (ACTIVITY_UPDATED_PROFILE, 'Updated your profile'),
        (ACTIVITY_SENT_MESSAGE, 'Sent a message'),
        (ACTIVITY_SOCIAL_SHARE, 'Shared via social a network'),
    )